[package]
name = "nexplore"
version = "0.1.0"
edition = "2021"
authors = ["Garry O'Donnell <garry.euan.odonnell@ntlworld.com>"]
description = "A Terminal User Interface (TUI) for exploring hdf5 & NeXus files"
license = "MIT OR Apache-2.0"
keywords = ["hdf5", "nexus", "tui"]
categories = ["command-line-utilities", "science", "visualization"]
repository = "https://github.com/garryod/nexplore"

[dependencies]
anyhow = { version = "1.0.72" }
clap = { version = "4.3.12", features = ["derive"] }
crossterm = { version = "0.26.1" }
derive_more = { version = "0.99.17" }
hdf5 = { version = "0.8.1" }
humansize = "2.1.3"
ratatui = { version = "0.21.0" }
